### ISSUE TITLE
"Internal Server Error" when syncing spreadsheets

### ISSUE THREAD

**Issue by tmfrnz** [jsoma/flatware#7]
After having successfully run flatware for more than a year, since last week syncing spreadsheets from the web interface fails with a "Internal Server Error" response for 2 independent installations on Heroku

**Comment by jengalas** [comment]
I'm having the same problem, all of a sudden. I'm using the latest version of Flatware. Syncing from the command line fails, too.

**Comment by jsoma** [comment]
Something weird is going on and I can't quite figure out what. The error is when connecting to S3:

`Excon::Errors::SocketError - unknown SSL method `TLSv1_2'. (ArgumentError)`

Which is what I changed to a few weeks ago to support the newest non-SSLv3-supporting version of S3. It works for me locally, though, so it seems like maybe it's something specific to Heroku? If someone ever comes to the rescue of [this SO question](http://stackoverflow.com/questions/30853564/argumenterror-unknown-ssl-method-tlsv1-2) we'll have our solution!

**Comment by jengalas** [comment]
`:ssl_version => :TLSv1` seems to work, but I suspect there are as many issues with TSLv1 as with SSLv3. Might be a starting point, though.

**Comment by jengalas** [comment]
I set up an instance on OpenShift and I'm getting the same "Internal Server Error," so it's not specific to just Heroku.

**Comment by tmfrnz** [comment]
The [question](http://stackoverflow.com/questions/30853564/argumenterror-unknown-ssl-method-tlsv1-2)  seems to be resolved. How does it solve this issue?

**Comment by tmfrnz** [comment]
@jsoma, if you can point me in the right direction, I am happy to dedicate some time to resolve this issue in the upcoming weeks... how do I best proceed?

**Comment by tmfrnz** [comment]
latest version + new IAM users = worksforme 
closing issue...
